DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
LOGS_BASEPATH=$DIR/logs

# DATE_NOW=$(date +"%Y-%m-%d-%H%M")
DATE_NOW=$(date +"%Y-%m-%d")

ATLAS_FETCH_BASE_LOGFILE=$LOGS_BASEPATH/otd_fetch_csv_atlas-lines
ATLAS_FETCH_LOGFILE=$ATLAS_FETCH_BASE_LOGFILE-$DATE_NOW.log
$DIR/python3 $DIR/cli_otd_fetch_csv_package.py --package_id slnid-line 2>&1 | tee $ATLAS_FETCH_LOGFILE

ATLAS_FETCH_LATEST_LOGFILE=$ATLAS_FETCH_BASE_LOGFILE-LATEST.log
rm -f $ATLAS_FETCH_LATEST_LOGFILE
ln -s $ATLAS_FETCH_LOGFILE $ATLAS_FETCH_LATEST_LOGFILE

ATLAS_GEOCODE_BASE_LOGFILE=$LOGS_BASEPATH/otd_geocode_atlas-lines
ATLAS_GEOCODE_LOGFILE=$ATLAS_GEOCODE_BASE_LOGFILE-$DATE_NOW.log
npm --prefix ../atlas-geocode-lines/ run process_node18 2>&1 | tee $ATLAS_GEOCODE_LOGFILE

ATLAS_GEOCODE_LATEST_LOGFILE=$ATLAS_GEOCODE_BASE_LOGFILE-LATEST.log
rm -f $ATLAS_GEOCODE_LATEST_LOGFILE
ln -s $ATLAS_GEOCODE_LOGFILE $ATLAS_GEOCODE_LATEST_LOGFILE
