map_sql_queries:
  select_calendar_dates_group_by: "[APP_PATH]/inc/sql/select_calendar_dates_group_by.sql"
  select_stop_times_group_by: "[APP_PATH]/inc/sql/select_trips_group_by_stop_times.sql"
  select_trips_group_by_stop_times_frequencies: "[APP_PATH]/inc/sql/select_trips_group_by_stop_times_frequencies.sql"
  update_stop_times_reset: "[APP_PATH]/inc/sql/update_stop_times_reset.sql"
  select_route_trips_calendar_day_bits: "[APP_PATH]/inc/sql/select_route_trips_calendar_day_bits.sql"
  create_fts_routes: "[APP_PATH]/inc/sql/create_fts_routes.sql"
  update_routes_representative_trip: "[APP_PATH]/inc/sql/update_routes_representative_trip.sql"

other_config_paths:
  scripts_config: "[APP_PATH]/inc/config/scripts-config.yml"

gtfs_dbs_base_path: "[APP_PATH]/data/gtfs-static-dbs"
gtfs_ckan_json_path: "[APP_PATH]/data/ckan-utils-tmp/ckan_[PACKAGE_ID].json"
gtfs_dbs_json_path: "[APP_PATH]/data/gtfs-static-dbs/gtfs-static-dbs.json"

bo_realtime_csv_path: "[APP_PATH]/data/opentransportdata.swiss/go-realtime/go-realtime.csv"

gtfs_rt_updates:
  -
    # up to 10.04 the GTFS-RT switch was done at 13:05 in the day of GTFS static publish
    to: "2024-04-10"
    switch: "13:05"
  -
    # up to 2025/2026 GTFS-RT switch was done at 15:05
    to: "2026-01-01"
    switch: "15:05"
  -
    # up to LATE-LATE the GTFS-RT switch is done at 15:00
    to: "2099-12-31"
    switch: "15:00"

gtfs_filter:
  sql:
    populate-link_filter: "[APP_PATH]/inc/sql/gtfs-filter/01-populate-link_filter.sql"
    select_table_template: "[APP_PATH]/inc/sql/gtfs-filter/02-run-[TABLE_NAME].sql"
  gtfs_export_profile: "[APP_PATH]/inc/config/gtfs_profile_ch.yml"
  db_config:
    tables:
      # holds trip_id that will be filtered
      link_filter_trips:
        columns:
          - trip_id TEXT PRIMARY KEY
