data_paths:
  gtfs-db-lookups: [APP_PATH]/data/gtfs-db-lookups
  gtfs-rt-snapshot: [APP_PATH]/data/gtfs-rt-snapshot
  gtfs-rt-static-compare-report: [APP_PATH]/data/gtfs-rt-static-compare-report
  gtfs-rt-static-compare-tmp: [APP_PATH]/data/gtfs-rt-static-compare-tmp
  gtfs-static: &GTFS_STATIC_DATA_PATH [APP_PATH]/data/opentransportdata.swiss/gtfs-static
  gtfs-static-dbs: &GTFS_STATIC_DBS_PATH [APP_PATH]/data/gtfs-static-dbs
  gtfs-query-db-cache: [APP_PATH]/data/gtfs-query-db-cache
  
  hrdf-query-db-cache: [APP_PATH]/data/hrdf-query-db-cache
  hrdf-opentransportdata.swiss: &HRDF_DATA_PATH [APP_PATH]/data/opentransportdata.swiss/hrdf
  hrdf-dbs: &HRDF_DBS_PATH [APP_PATH]/data/hrdf-dbs
  hrdf-db-lookups: [APP_PATH]/data/hrdf-db-lookups
  hrdf-duplicates-reports: [APP_PATH]/data/hrdf-duplicates-reports
  hrdf-duplicates-reports-csv: [APP_PATH]/data/hrdf-duplicates-reports/hrdf-duplicates-reports-csv

  go_data: [APP_PATH]/data/opentransportdata.swiss/business-organisations
  go_latest: [APP_PATH]/data/opentransportdata.swiss/business-organisations/actual_date_business_organisation_versions_LATEST.csv

resource_paths:
  ckan_gtfs_static_json: [APP_PATH]/data/ckan-utils-tmp/ckan_gtfs_static.json
  ckan_go_json: [APP_PATH]/data/ckan-utils-tmp/ckan_business-organisations.json
