env_file_version: '1'
env_file_path: [APP_PATH]/.ENV.LOCAL

tmp-data-paths:
  gtfs-static: &GTFS_STATIC_DATA_PATH [APP_PATH]/tmp/opentransportdata.swiss/gtfs-static
  gtfs-static-dbs: &GTFS_STATIC_DBS_PATH [APP_PATH]/tmp/gtfs-static-dbs
  gtfs-query-db-cache: [APP_PATH]/tmp/gtfs-query-db-cache
  hrdf-opentransportdata.swiss: &HRDF_DATA_PATH [APP_PATH]/tmp/opentransportdata.swiss/hrdf
  hrdf-dbs: &HRDF_DBS_PATH [APP_PATH]/tmp/hrdf-dbs

env_data_keys:
  GTFS_STATIC_DATA_PATH: *GTFS_STATIC_DATA_PATH
  GTFS_STATIC_DBS_PATH: *GTFS_STATIC_DBS_PATH
  HRDF_DATA_PATH: *HRDF_DATA_PATH
  HRDF_DBS_PATH: *HRDF_DBS_PATH