current_package_ids:
  gtfs: timetable-2025-gtfs2020
  hrdf: timetable-54-2025-hrdf

csv_latest_data:  
  # https://data.opentransportdata.swiss/en/dataset/business-organisations
  business-organisations:
    example: actual_date_business_organisation_versions_2025-01-17.csv
    file_prefix: actual_date_business_organisation_versions
    symlink_latest_path: "[APP_PATH]/data/opentransportdata.swiss/[PACKAGE_ID]/[PREFIX]_LATEST.csv"
  
  # https://data.opentransportdata.swiss/en/dataset/go-realtime
  go-realtime:
    example: go-realtime.csv
  
  # https://data.opentransportdata.swiss/en/dataset/slnid-line
  slnid-line:
    example: actual_date_line_versions_2025-01-17.csv
    file_prefix: actual_date_line_versions
    symlink_latest_path: "[APP_PATH]/data/opentransportdata.swiss/[PACKAGE_ID]/[PREFIX]_LATEST.csv"

data_paths:
  opentransportdata:
    package_base_path: "[APP_PATH]/data/opentransportdata.swiss/[PACKAGE_ID]"

  gtfs-db-lookups: "[APP_PATH]/data/gtfs-db-lookups"
  gtfs-rt-snapshot: "[APP_PATH]/data/gtfs-rt-snapshot"
  gtfs-rt-static-compare-report: "[APP_PATH]/data/gtfs-rt-static-compare-report"
  gtfs-rt-static-compare-tmp: "[APP_PATH]/data/gtfs-rt-static-compare-tmp"
  gtfs-static-dbs: "[APP_PATH]/data/gtfs-static-dbs"
  gtfs-query-db-cache: "[APP_PATH]/data/gtfs-query-db-cache"
  
  hrdf-query-db-cache: "[APP_PATH]/data/hrdf-query-db-cache"
  hrdf-dbs: "[APP_PATH]/data/hrdf-dbs"
  hrdf-db-lookups: "[APP_PATH]/data/hrdf-db-lookups"
  hrdf-duplicates-reports: "[APP_PATH]/data/hrdf-duplicates-reports"
  hrdf-duplicates-reports-csv: "[APP_PATH]/data/hrdf-duplicates-reports/hrdf-duplicates-reports-csv"

resource_paths:
  ckan_metadata_path: "[APP_PATH]/data/ckan-utils-tmp/ckan_[PACKAGE_ID].json"
