data_paths:
  gtfs-static: &GTFS_STATIC_DATA_PATH [APP_PATH]/data/opentransportdata.swiss/gtfs-static
  gtfs-static-dbs: &GTFS_STATIC_DBS_PATH [APP_PATH]/data/gtfs-static-dbs
  gtfs-query-db-cache: [APP_PATH]/data/gtfs-query-db-cache
  hrdf-query-db-cache: [APP_PATH]/data/hrdf-query-db-cache
  hrdf-opentransportdata.swiss: &HRDF_DATA_PATH [APP_PATH]/data/opentransportdata.swiss/hrdf
  hrdf-dbs: &HRDF_DBS_PATH [APP_PATH]/data/hrdf-dbs
  hrdf-db-lookups: [APP_PATH]/data/hrdf-db-lookups
  hrdf-duplicates-reports: [APP_PATH]/data/hrdf-duplicates-reports
  hrdf-duplicates-reports-csv: [APP_PATH]/data/hrdf-duplicates-reports/hrdf-duplicates-reports-csv
