app_path: "[APP_PATH]"

ojp_gtfs_dbs_path: "[APP_PATH]/data/gtfs-static-dbs"
gtfs_dbs_catalog_path: "[APP_PATH]/data/gtfs-static-dbs/gtfs-static-dbs.json"

# https://opentransportdata.swiss/en/dataset/business-organisations
business_organisation_latest_path: "[APP_PATH]/data/opentransportdata.swiss/business-organisations/actual_date_business_organisation_versions_LATEST.csv"
# https://opentransportdata.swiss/de/dataset/go-realtime
go_realtime_csv_path: "[APP_PATH]/data/opentransportdata.swiss/go-realtime/business_organisation_realtime_LATEST.csv"

map_sql_queries:
    # select
    query_day_trips: "[APP_PATH]/inc/sql/gtfs/query_day_trips.sql"
    # where
    where_from_to_trips: "[APP_PATH]/inc/sql/gtfs/where/where_from_to_trips.sql"
    # fields
    fields_query_day_full_trips: "[APP_PATH]/inc/sql/gtfs/fields/query_day_full_trips.sql"
    fields_query_day_light_trips: "[APP_PATH]/inc/sql/gtfs/fields/query_day_light_trips.sql"

sql_builder_path: "[APP_PATH]/inc/config/sql_builder.yml"

app_db_cache_path: "[APP_PATH]/data/gtfs-query-db-cache"
