resource_paths:
  app_path: [APP_PATH]
  dotenv_path: [APP_PATH]/../../.env
  gtfs_rt_snapshot: [APP_PATH]/data/gtfs-rt-snapshot/[YEAR]/[MONTH]/[DAY]/GTFS_RT-[YEAR]-[MONTH]-[DAY]-[HHMM].json
  gtfs_db: [APP_PATH]/data/gtfs-static-dbs/[GTFS_FILENAME]
  gtfs_dbs_json_path: [APP_PATH]/data/gtfs-static-dbs/gtfs-static-dbs.json
  cache_gtfs_db_table: [APP_PATH]/data/gtfs-rt-static-compare-tmp/[GTFS_FILENAME].[TABLE_NAME]-v1.json
  gtfs_rt_static_report: [APP_PATH]/data/gtfs-rt-static-compare-report/[YEAR]/[MONTH]/[DAY]/gtfs_rt_static_report-[YEAR]-[MONTH]-[DAY]-[HHMM].json
  gtfs_rt_static_mo_json: [APP_PATH]/data/gtfs-rt-static-compare-report/[YEAR]/gtfs_rt_static_report-[YEAR]-[MONTH].json

opentransportdata:
  gtfs_rt_url: https://api.opentransportdata.swiss/la/gtfs-rt?format=JSON

# following days are still included in drop line computation even though they had errors
map_days_ignore_dropline_error:
  "2025-10-23": yes
  "2025-10-24": yes
  "2025-10-27": yes
  "2025-10-28": yes

# TODO - needs to be generated
map_holidays:
  # 2024
  "2024-01-01": New Years
  "2024-01-02": Berchtold's Day
  "2024-03-28": Maundy Thursday
  "2024-04-01": Easter Monday
  "2024-05-09": Ascension Day
  "2024-05-20": Whit Monday
  "2024-08-01": National Day
  "2024-12-25": Christmas Day
  "2024-12-26": Saint Stephen's Day
  
  # 2025
  "2025-01-01": New Years
  "2025-01-02": Berchtold's Day
  "2025-04-17": Maundy Thursday
  "2025-04-21": Easter Monday
  "2025-05-29": Ascension Day
  "2025-06-09": Whit Monday
  "2025-08-01": National Day
  "2025-12-25": Christmas Day
  "2025-12-26": Saint Stephen's Day
  
  # 2026
  "2026-01-01": New Years
  "2026-01-02": Berchtold's Day
  "2026-04-02": Maundy Thursday
  "2026-04-06": Easter Monday
  "2026-05-14": Ascension Day
  "2026-05-25": Whit Monday
  "2026-08-01": National Day
  "2026-12-25": Christmas Day
  "2026-12-26": Saint Stephen's Day

  # 2027
  "2027-01-01": New Years
  "2027-01-02": Berchtold's Day
  "2027-03-25": Maundy Thursday
  "2027-03-29": Easter Monday
  "2027-05-06": Ascension Day
  "2027-05-17": Whit Monday
  "2027-08-01": National Day
  "2027-12-25": Christmas Day
  "2027-12-26": Saint Stephen's Day

