resource_paths:
  gtfs_rt_snapshot: [APP_PATH]/data/gtfs-rt-snapshot/[YEAR]/[MONTH]/[DAY]/GTFS_RT-[YEAR]-[MONTH]-[DAY]-[HHMM].json
  gtfs_db: [APP_PATH]/data/gtfs-static-dbs/[GTFS_FILENAME]
  cache_gtfs_db_table: [APP_PATH]/data/gtfs-rt-static-compare-tmp/[GTFS_FILENAME].[TABLE_NAME]-v1.json
  gtfs_rt_static_report: [APP_PATH]/data/gtfs-rt-static-compare-report/[YEAR]/[MONTH]/[DAY]/gtfs_rt_static_report-[YEAR]-[MONTH]-[DAY]-[HHMM].json
  gtfs_rt_static_mo_report: [APP_PATH]/data/gtfs-rt-static-compare-report/[YEAR]/[MONTH]/gtfs_rt_static_report-[YEAR]-[MONTH].html
  gtfs_rt_static_mo_json: [APP_PATH]/data/gtfs-rt-static-compare-report/[YEAR]/gtfs_rt_static_report-[YEAR]-[MONTH].json

opentransportdata:
  key: eyJvcmciOiI2NDA2NTFhNTIyZmEwNTAwMDEyOWJiZTEiLCJpZCI6IjY2ZWIyNGRjMjJlNDQ4OGJhYzUxZDFkY2M4ZjhkMjFlIiwiaCI6Im11cm11cjEyOCJ9
  gtfs_rt_url: https://api.opentransportdata.swiss/gtfsrt2020?FORMAT=json
