map_sql_queries:
  hrdf_select_trips: [APP_PATH]/inc/sql/hrdf_select_trips.sql

report_paths:
  hrdf_duplicates_report_path: [APP_PATH]/data/hrdf-duplicates-reports/hrdf_duplicates_report_[HRDF_YMD].json
