sql_builder:
  query_routes:
    fields:
      - route_id
      - agency_id
      - route_short_name
      - route_long_name
      - route_desc
      - route_type
    where:
      - "1=1"
    tables:
      - routes
  
  query_trips:
    fields:
      - trips.trip_id
      - trips.trip_short_name
      - trips.departure_time
      - trips.arrival_time
      - trips.departure_day_minutes
      - trips.arrival_day_minutes
      - trips.trip_headsign

      - routes.route_id
      - routes.route_type
      - routes.route_short_name

      - agency.agency_id
      - agency.agency_name

      - trips.stop_times_s

      - calendar.day_bits
    tables:
      - trips
      - calendar
      - routes
      - agency
    where:
      - trips.service_id = calendar.service_id 
      - trips.route_id = routes.route_id
      - routes.agency_id = agency.agency_id
    limit: 100
