opentransportdata.swiss:
  ckan_package_url: https://api.opentransportdata.swiss/ckan-api/package_show?id=[package_id]
  authorization: 57c5dbbbf1fe4d000100001842c323fa9ff44fbba0b9b925f0c052d1

hrdf_5.4:
  package_id: timetable-54-2022-hrdf